### ISSUE TITLE
Melhorar o README

### ISSUE THREAD

**Issue by arthurs159** [vitormarcato/media-equipment-rental-system#2]
Readme é o primeiro contato com o projeto que qualquer pessoa vai ter, e muitas vezes o recrutador nem sabe codar, então ele não irá baixar seu projeto para testar. Isso faz o readme mais importante ainda. Eu recomendo colocar um briefing do projeto, quais foram os seus objetivos ao fazer esse projeto, porque decidiu fazer ele, vi que você colocou um video, ficou muito bom!!! Dizer também coisas que aprendeu ao fazer esse projeto é bem importante!!!

**Comment by vitormarcato** [comment]
realizei a atualização do readme com uma nova seção chamda WHY onde apresentei brevemente o objetivo do projeto,  porque decidi fazer  e o que eu aprendi e apliquei no código.
